# Generated by Django 5.1.2 on 2024-10-23 09:46

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('image', models.ImageField(upload_to=apps.utils.custom_upload_path, verbose_name='Фото')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Событии',
            },
        ),
    ]
